@extends('layouts.app')
@section('title', 'Mijn profiel - Servura Admin')
@section('content')
@include('admin.partials.sidebar')
<div class="min-h-screen bg-slate-50 lg:pl-64"><main class="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
<h1 class="text-2xl font-bold text-slate-900">Mijn profiel</h1><p class="mt-1 text-sm text-slate-600">Beheer uw persoonlijke gegevens, inloggegevens en tickethandtekening.</p>
@if(session('success'))<div class="mt-6 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800 ring-1 ring-emerald-200">{{ session('success') }}</div>@endif
<form method="POST" action="{{ route('admin.profile.update') }}" class="mt-6 flex flex-col gap-6">@csrf @method('PUT')
<section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="font-semibold text-slate-900">Persoonlijke gegevens</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label class="form-label">Naam</label><input name="name" value="{{ old('name', $user->name) }}" class="form-input mt-1 w-full" required>@error('name')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label">Telefoonnummer</label><input name="phone" value="{{ old('phone', $user->phone) }}" class="form-input mt-1 w-full"></div><div class="sm:col-span-2"><label class="form-label">E-mailadres</label><input type="email" name="email" value="{{ old('email', $user->email) }}" class="form-input mt-1 w-full" required>@error('email')<p class="form-error">{{ $message }}</p>@enderror</div></div></section>
<section class="rounded-2xl bg-slate-900 p-6 text-white shadow-xl shadow-slate-900/10"><h2 class="font-semibold">Tickethandtekening</h2><p class="mt-1 text-sm text-slate-300">Wordt automatisch onder iedere openbare ticketreactie geplaatst. Interne notities krijgen geen handtekening.</p><textarea name="ticket_signature" rows="6" class="mt-5 w-full rounded-xl border border-white/15 bg-white/10 p-4 text-sm text-white placeholder:text-slate-400 focus:border-primary-400 focus:outline-none focus:ring-2 focus:ring-primary-400/20" placeholder="Met vriendelijke groet,&#10;{{ $user->name }}&#10;{{ config('app.name') }}">{{ old('ticket_signature', $user->ticket_signature) }}</textarea>@error('ticket_signature')<p class="mt-2 text-sm text-rose-300">{{ $message }}</p>@enderror</section>
<section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="font-semibold text-slate-900">Wachtwoord wijzigen</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="form-label">Huidig wachtwoord</label><input type="password" name="current_password" class="form-input mt-1 w-full" autocomplete="current-password">@error('current_password')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label">Nieuw wachtwoord</label><input type="password" name="password" class="form-input mt-1 w-full" autocomplete="new-password"></div><div><label class="form-label">Bevestig nieuw wachtwoord</label><input type="password" name="password_confirmation" class="form-input mt-1 w-full" autocomplete="new-password"></div></div></section>
<div class="flex justify-end"><button class="btn btn-primary">Profiel opslaan</button></div></form></main></div>
@endsection
