@extends('layouts.app')
@section('title', 'Medewerkers - Servura Admin')
@section('content')
@include('admin.partials.sidebar')
<div class="min-h-screen bg-slate-50 lg:pl-64"><main class="mx-auto max-w-[1600px] px-4 py-8 sm:px-6 lg:px-8">
<h1 class="text-2xl font-bold text-slate-900">Medewerkers</h1><p class="mt-1 text-sm text-slate-600">Beheer toegang tot het adminpaneel.</p><div class="mt-6">@include('admin.partials.settings-nav')</div>
@if(session('success'))<div class="mb-6 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800 ring-1 ring-emerald-200">{{ session('success') }}</div>@endif
<div class="grid gap-6 xl:grid-cols-[24rem_1fr]">
<form method="POST" action="{{ route('admin.settings.staff.store') }}" class="h-fit rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">@csrf<h2 class="font-semibold text-slate-900">Account toevoegen</h2>
<div class="mt-5 space-y-4"><div><label class="form-label">Naam</label><input name="name" value="{{ old('name') }}" class="form-input mt-1 w-full" required></div><div><label class="form-label">E-mailadres</label><input type="email" name="email" value="{{ old('email') }}" class="form-input mt-1 w-full" required></div><div><label class="form-label">Rol</label><select name="role" class="form-input mt-1 w-full"><option value="employee">Medewerker</option><option value="admin">Administrator</option></select></div><div><label class="form-label">Tijdelijk wachtwoord</label><input type="password" name="password" class="form-input mt-1 w-full" minlength="12" required></div><div><label class="form-label">Bevestig wachtwoord</label><input type="password" name="password_confirmation" class="form-input mt-1 w-full" required></div></div><button class="btn btn-primary mt-5 w-full">Account aanmaken</button></form>
<div class="space-y-4">@foreach($staff as $member)<form method="POST" action="{{ route('admin.settings.staff.update', $member) }}" class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200">@csrf @method('PUT')
<div class="flex flex-col gap-4 lg:flex-row lg:items-end"><div class="grid flex-1 gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><label class="form-label">Naam</label><input name="name" value="{{ $member->name }}" class="form-input mt-1 w-full" {{ $member->isOwner() ? 'disabled' : '' }}></div><div><label class="form-label">E-mail</label><input type="email" name="email" value="{{ $member->email }}" class="form-input mt-1 w-full" {{ $member->isOwner() ? 'disabled' : '' }}></div><div><label class="form-label">Rol</label><select name="role" class="form-input mt-1 w-full" {{ $member->isOwner() ? 'disabled' : '' }}><option value="employee" @selected($member->role==='employee')>Medewerker</option><option value="admin" @selected($member->role==='admin')>Administrator</option><option value="owner" @selected($member->role==='owner')>Eigenaar</option></select></div><div><label class="form-label">Laatste login</label><div class="mt-1 py-2.5 text-sm text-slate-600">{{ $member->last_login_at?->format('d-m-Y H:i') ?? 'Nog nooit' }}</div></div></div>
@if(!$member->isOwner())<div class="flex items-center gap-2"><label class="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" name="is_active" value="1" @checked($member->is_active) class="rounded"> Actief</label><button class="btn btn-outline">Opslaan</button></div>@else<span class="rounded-lg bg-primary-50 px-3 py-2 text-sm font-semibold text-primary-700">Eigenaar</span>@endif</div>
@if(!$member->isOwner())<div class="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2"><input type="password" name="password" placeholder="Nieuw wachtwoord (optioneel)" class="form-input"><div class="flex gap-2"><input type="password" name="password_confirmation" placeholder="Bevestigen" class="form-input flex-1"><button type="submit" formmethod="POST" formaction="{{ route('admin.settings.staff.destroy', $member) }}" name="_method" value="DELETE" class="rounded-lg px-3 text-sm font-semibold text-red-600 hover:bg-red-50" onclick="return confirm('Dit medewerkeraccount verwijderen?')">Verwijderen</button></div></div>@endif
</form>@endforeach</div></div></main></div>
@endsection
