<nav class="mb-6 flex gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1" aria-label="Instellingen">
    <a href="{{ route('admin.settings.general') }}" class="whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors {{ request()->routeIs('admin.settings.general*') ? 'bg-white text-primary-700 shadow-sm ring-1 ring-slate-200' : 'text-slate-600 hover:bg-white/70 hover:text-slate-900' }}">Algemeen</a>
    <a href="{{ route('admin.settings.mail') }}" class="whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors {{ request()->routeIs('admin.settings.mail*') ? 'bg-white text-primary-700 shadow-sm ring-1 ring-slate-200' : 'text-slate-600 hover:bg-white/70 hover:text-slate-900' }}">Mail</a>
    <a href="{{ route('admin.settings.email-templates') }}" class="whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors {{ request()->routeIs('admin.settings.email-templates*') ? 'bg-white text-primary-700 shadow-sm ring-1 ring-slate-200' : 'text-slate-600 hover:bg-white/70 hover:text-slate-900' }}">E-mailtemplates</a>
    <a href="{{ route('admin.settings.payments') }}" class="whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors {{ request()->routeIs('admin.settings.payments*') ? 'bg-white text-primary-700 shadow-sm ring-1 ring-slate-200' : 'text-slate-600 hover:bg-white/70 hover:text-slate-900' }}">Betalingen</a>
    <a href="{{ route('admin.settings.billing') }}" class="whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors {{ request()->routeIs('admin.settings.billing*', 'admin.financial.billing-settings*') ? 'bg-white text-primary-700 shadow-sm ring-1 ring-slate-200' : 'text-slate-600 hover:bg-white/70 hover:text-slate-900' }}">Facturatie</a>
    <a href="{{ route('admin.settings.formbuilder') }}" class="whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors {{ request()->routeIs('admin.settings.formbuilder*') ? 'bg-white text-primary-700 shadow-sm ring-1 ring-slate-200' : 'text-slate-600 hover:bg-white/70 hover:text-slate-900' }}">Offerteformulier</a>
    <a href="{{ route('admin.settings.security') }}" class="whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors {{ request()->routeIs('admin.settings.security*') ? 'bg-white text-primary-700 shadow-sm ring-1 ring-slate-200' : 'text-slate-600 hover:bg-white/70 hover:text-slate-900' }}">Beveiliging</a>
    <a href="{{ route('admin.settings.newsletter') }}" class="whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors {{ request()->routeIs('admin.settings.newsletter*') ? 'bg-white text-primary-700 shadow-sm ring-1 ring-slate-200' : 'text-slate-600 hover:bg-white/70 hover:text-slate-900' }}">Nieuwsbrief</a>
    <a href="{{ route('admin.server-connections.index') }}" class="whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors {{ request()->routeIs('admin.server-connections.*') ? 'bg-white text-primary-700 shadow-sm ring-1 ring-slate-200' : 'text-slate-600 hover:bg-white/70 hover:text-slate-900' }}">Serverkoppelingen</a>
</nav>
